title: About me
author: X0SS
email: jupi4r@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is "X" Age 14 My birthday is 11/07/2006 I'm studied on Grade 10
  I like to play games and coding I just want new pc :)

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
---
title: "About me"
date: 2021-04-24
---
